spring:
  h2:
    console:
      path: '/h2-console'
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    password: 
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        formater-sql: true

api:
  produtos:
    url: http://localhost:8080/produtos